language: go
before_deploy:
  - go get -u github.com/laher/goxc
  - mkdir -p $TRAVIS_BUILD_DIR/dist
  - goxc -d=$TRAVIS_BUILD_DIR/dist -bc="linux,!arm darwin" -tasks=clean-destination,xc,archive,rmbin
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: KsiCOqlHVtVONmFWFNP5b/4dDmb9S71VussAPVbPXW4ZwLlcLq1P1IKvppjUfg9XBonhzLQdpS03VQmnjLlSwcqvzcTDY1tW1Z9JZSoX32az/wlLST+LNdCR6rQRkxzV8Okc4lN8TR1tWy01W9PZS6Ps+xFabT9q5cDFhgL3Yf8p6+xBINMQCc6K2WzvC8z3qo8pVzAWjSEIp5JrgYffxoTACs6icDeMA38n75YI/m2AmBKeVotEzG2ajafPKDsWtn0ZFjT6AG0W+eUpJTHl4ylCmF4x7AVMpbrmlK49h+LIURuy5uUg4UX2KObQCXxcI7zwMJD8XzvO0n28eD+ZaDP4q03SvDifmAmAKhr1V55hIUOweG4HbcLRbAyDyQPm95cW2X/CNuA0lmovYXlYAfafllMRsywCSWvIG+RXjDnKfRlhPEckenZDw+DnYG0bFB0YOhlH9bojVY0i5uh5FTTie4hh/NaBmnCzi5IfOHJkGKmVzAkSfG2/xnXheIon/jR0QMa1jnfeanmaGl0BZJO9DyBOkN/kcbHL35Y5xW5NuyiRAFlR3t5lHNmns9pzX3teDHG3lLX5TfOVqPA75G9PQwDaTiEb//hnVAhmD29NUJfbHxFGVpRdTCKJtY24mRi+Oqaf6l1VD2C6yzkns/xjStjtyuHLoZ+v4wBD6I8=
  file_glob: true
  file: $TRAVIS_BUILD_DIR/dist/**/*.{tar.gz,zip}
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
